baseURL = "https://devops-monk.com/"
languageCode = "en-us"
title = "Devops Monk"
theme = "wellington"
paginate=10

disqusShortname = "devopsmonk"
googleAnalytics = "UA-71296890-1"
enableRobotsTXT = true
preserveTaxonomyNames = true

[taxonomies]
  category = "categories"
  tag = "tags"

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params]
  author = "Abhay"
  subtitle = ""
  description = ""
  email = "abhaypratap3536@gmail.com"
  github = "abhi15sep"
  linkedin = "abhay-singh-831997b5"

